In [2]:
import pandas as pd
login_2016_2022_df = pd.read_csv("/Users/leeliang/Desktop/dashboard_registration/login_2016to2022.csv")
login_2016_2022_df

      date  2016  2017  2018  2019  2020  2021  2022
0    01-01   329   401   328   314   641   734   886
1    01-02   399   550   554   407   808   871  1336
2    01-03   482   628   513   477   802  1121  1527
3    01-04   562   780   414   419   583  1622  1688
4    01-05   496   803   425   369   637  1615  1461
..     ...   ...   ...   ...   ...   ...   ...   ...
360  12-27   668   445   447   758  1328  2151  2012
361  12-28   569   499   465   667  1642  1792  1566
362  12-29   732   425   336   700  1362  1445  1853
363  12-30   598   308   353   860  1449  1416  1698
364  12-31   581   270   265   686  1114   820   821

[365 rows x 8 columns]

In [16]:
login_melt_df = login_2016_2022_df.melt(id_vars=["date"])
date_done_df = pd.to_datetime(login_melt_df["variable"] + "-" + login_melt_df["date"])
date_login_df = pd.concat([date_done_df.rename("date"), login_melt_df["value"]], axis = 1)
date_login_df

           date  value
0    2016-01-01    329
1    2016-01-02    399
2    2016-01-03    482
3    2016-01-04    562
4    2016-01-05    496
...         ...    ...
2550 2022-12-27   2012
2551 2022-12-28   1566
2552 2022-12-29   1853
2553 2022-12-30   1698
2554 2022-12-31    821

[2555 rows x 2 columns]

In [17]:
date_login_df.to_csv("/Users/leeliang/Desktop/dashboard_registration/login_20162022_done.csv")

In [21]:
login_20162022_raw = pd.read_csv("/Users/leeliang/Desktop/dashboard_registration/login_2016-2022.csv")
login_20162022_raw

      date  2016  2017  2018  2019  2020  2021  2022
0    01-01   329   401   328   314   641   734   886
1    01-02   399   550   554   407   808   871  1336
2    01-03   482   628   513   477   802  1121  1527
3    01-04   562   780   414   419   583  1622  1688
4    01-05   496   803   425   369   637  1615  1461
..     ...   ...   ...   ...   ...   ...   ...   ...
360  12-27   668   445   447   758  1328  2151  2012
361  12-28   569   499   465   667  1642  1792  1566
362  12-29   732   425   336   700  1362  1445  1853
363  12-30   598   308   353   860  1449  1416  1698
364  12-31   581   270   265   686  1114   820   821

[365 rows x 8 columns]

In [23]:
login_20162022_raw[login_20162022_raw["date"] == '01-01']["date"]

0    01-01
Name: date, dtype: object

In [24]:
import datetime
today = datetime.date.today()
print(today)
#tomorrow = today + datetime.timedelta(days=1)

2023-08-02

In [25]:
date_obj = datetime.datetime.strptime('01-02', '%m-%d')
print(date_obj)

1900-01-02 00:00:00

In [29]:
date = '09-06'
datetime.datetime.strptime(date, "%m-%d")
str(datetime.datetime.strptime(date, "%m-%d"))

'1900-09-06 00:00:00'

In [36]:
start_date = datetime.date(3, 1)
date_str = start_date.strftime('%Y-%m-%d')
print(start_date)

TypeError: function missing required argument 'day' (pos 3)

---

---

In [3]:
import pandas as pd
register20230717_df = pd.read_csv("/Users/leeliang/Desktop/dashboard_registration/registerdata20230717.csv")
register20230717_df

,firstname,lastname,email,country,city,unit,dept,title,age,jobstatus,company,gender,edulevel,timecreated,age_new,studystatus
0,玉秀,張,nzkc2001@apps.ntpc.edu.tw,TW,新北市,NaN,NaN,NaN,未填,未填,"""""",未填,未填,1/18/23 10:39,1/18/23 0:00,未填
1,閩華,張,ivy3226@chc.edu.tw,TW,"""""",NaN,NaN,NaN,未填,未填,"""""",未填,未填,1/18/23 10:52,1/18/23 0:00,未填
2,文偉,林,zx152364@gmail.com,TW,南投縣,NaN,NaN,NaN,未填,未填,"""""",未填,未填,1/18/23 11:01,1/18/23 0:00,未填
3,佳芬,何,annho62@kmjh.tc.edu.tw,TW,台中市,NaN,NaN,NaN,未填,未填,"""""",未填,未填,1/18/23 12:10,1/18/23 0:00,未填
4,謝美嬌,"""""",ops@ntpc.edu.tw,"""""","""""",NaN,NaN,NaN,未填,未填,NaN,未填,未填,1/18/23 13:37,1/1/70 8:00,未填
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37144,天佑,曾,vix1121@hotmail.com,TW,新北市,NaN,NaN,NaN,未填,未填,"""""",未填,未填,7/17/23 4:19,7/17/23 0:00,未填
37145,佩珊,謝,patty12260000@gmail.com,TW,桃園,NaN,NaN,NaN,未填,未填,"""""",未填,未填,7/17/23 6:54,7/17/23 0:00,未填
37146,庭芸,游,kelly861113@gmail.com,TW,宜蘭縣,NaN,NaN,NaN,未填,未填,"""""",未填,未填,7/17/23 7:09,7/17/23 0:00,未填
37147,Anthony,Huang,mr884347@gmail.com,TW,Hsinchu,NaN,NaN,NaN,未填,未填,"""""",未填,未填,7/17/23 8:04,7/17/23 0:00,未填
37148,貴琦,王,ykk333@gmail.com,TW,台北市,NaN,NaN,NaN,未填,未填,"""""",未填,未填,7/17/23 8:40,7/17/23 0:00,未填

In [41]:
# putting lastname in firstname column
for i in range(register20230717_df.shape[0]):
    if register20230717_df["lastname"].iloc[i] == '""':
        new_firstname = register20230717_df["firstname"].iloc[i][1:]
        new_lastname = register20230717_df["firstname"].iloc[i][0]
        register20230717_df["lastname"].iloc[i] = new_lastname
        register20230717_df["firstname"].iloc[i] = new_firstname

register20230717_df.head(20)

/var/folders/jb/dqyqqwzs7s335q1r73w5cpg00000gn/T/ipykernel_40262/406749099.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/jb/dqyqqwzs7s335q1r73w5cpg00000gn/T/ipykernel_40262/406749099.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,firstname,lastname,email,country,city,timecreated,age_new,studystatus,Y,M,W
0,玉秀,張,nzkc2001@apps.ntpc.edu.tw,TW,新北市,1/18/23 10:39,1/18/23 0:00,未填,2023,1,3
1,閩華,張,ivy3226@chc.edu.tw,TW,"""""",1/18/23 10:52,1/18/23 0:00,未填,2023,1,3
2,文偉,林,zx152364@gmail.com,TW,南投縣,1/18/23 11:01,1/18/23 0:00,未填,2023,1,3
3,佳芬,何,annho62@kmjh.tc.edu.tw,TW,台中市,1/18/23 12:10,1/18/23 0:00,未填,2023,1,3
4,美嬌,謝,ops@ntpc.edu.tw,"""""","""""",1/18/23 13:37,1/1/70 8:00,未填,2023,1,3
5,柏彥,鄭,mj100013@ntpc.edu.tw,"""""","""""",1/18/23 13:50,1/1/70 8:00,未填,2023,1,3
6,鼎祐,陳,edmund1124@ntpc.edu.tw,"""""","""""",1/18/23 13:50,1/1/70 8:00,未填,2023,1,3
7,冠縉,陳,sj655100@sish.ntpc.edu.tw,TW,新北市,1/18/23 13:51,1/18/23 0:00,未填,2023,1,3
8,鈞賀,陳,jack04100@ntpc.edu.tw,"""""","""""",1/18/23 13:54,1/1/70 8:00,未填,2023,1,3
9,瑞傑,鄭,noel0310@ntpc.edu.tw,"""""","""""",1/18/23 14:00,1/1/70 8:00,未填,2023,1,3
10,宜進,蔡,panzheshen@gmail.com,"""""","""""",1/18/23 14:00,1/18/23 0:00,未填,2023,1,3
11,睿哲,李,tyuhgvb1234@gmail.com,TW,新北市,1/18/23 14:01,1/18/23 0:00,未填,2023,1,3
12,志誠,李,sj655119@sish.ntpc.edu.tw,"""""","""""",1/18/23 14:02,1/18/23 0:00,未填,2023,1,3
13,翼宸,王,johnson655001@ntpc.edu.tw,TW,新北市,1/18/23 14:04,1/1/70 8:00,未填,2023,1,3
14,凱軍,沈,sj655045@sish.ntpc.edu.tw,TW,新北市,1/18/23 14:04,1/18/23 0:00,未填,2023,1,3
15,謙佑,林,sj655052@sish.ntpc.edu.tw,TW,新北市,1/18/23 14:07,1/22/05 0:00,未填,2023,1,3
16,映如,林,amystar0412@gmail.com,TW,桃園市,1/18/23 14:10,1/18/23 0:00,未填,2023,1,3
17,睿姿,林,bettyf229@gmail.com,"""""","""""",1/18/23 14:10,1/18/23 0:00,未填,2023,1,3
18,韋澔,林,dennylin.725@gmail.com,"""""","""""",1/18/23 14:14,1/18/23 0:00,未填,2023,1,3
19,玲如,林,lingru005@yahoo.com.tw,TW,台北市,1/18/23 15:03,11/13/64 0:00,未填,2023,1,3

## email/domain

In [61]:
email_list = register20230717_df["email"].values
domain_name_list = [i[i.index('@') + 1 : ] for i in email_list]
domain_name_unqiue_list = list(set(domain_name_list))
domain_name_unqiue_list

['seasideinteractive.com',
 'd.bigman.monster',
 'skjhs.ntct.edu.tw',
 'yahoo.co.id',
 'ckes.tc.edu.tw',
 'student.ltsh.ilc.edu.tw',
 'e.shavers.hair',
 'webmail.ccsh.tp.edu.tw',
 'sssh.tyc.edu.tw',
 'gm.sysh.tc.edu.tw',
 'smail.nchu.edu.tw',
 'ems.tcust.edu.tw',
 'kbbrenders.co.uk',
 'mdhs.tc.edu.tw',
 'sphs.hc.edu.tw',
 'clhs.tyc.edu.tw',
 'ms2.ttc.edu.tw',
 'ghwjps.kh.edu.tw',
 'spinrewriter.app',
 'ms38.hinet.net',
 'c.shavers.hair',
 'hermes.com.tw',
 'sdhs.ntpc.edu.tw',
 'amaill.xyz',
 'npm.gov.tw',
 'nextgennation.store',
 'scjh.tc.edu.tw',
 'gml.klgsh.kl.edu.tw',
 'obesemen.ink',
 'cmgsh.tp.edu.tw',
 'shes.hcc.edu.tw',
 'waldorf.ilc.edu.tw',
 'go.pymhs.tyc.edu.tw',
 'guest.xlping.com',
 'ms53.hinet.net',
 'youngoptics.com',
 'cyhvs.cy.edu.tw',
 'nhush.tp.edu.tw',
 'SHIPGPL.COM',
 '189.cn',
 'go.utaipei.edu.tw',
 'chestpain.one',
 'mx.ilvs.ilc.edu.tw',
 'jjs.mlc.edu.tw',
 'basic.bekkr.com',
 'thb.gov.tw',
 'stu.tcvs.ilc.edu.tw',
 'ms.cshs.tc.edu.tw',
 'lcps.ntpc.edu.tw',
 'ms.tyc.edu.tw',
 'yuda.tyc.edu.tw',
 'kusjh.kh.edu.tw',
 'moe-dl.edu.my',
 'ms1.url.com.tw',
 'cysh.khc.edu.tw',
 'zlsh.tp.edu.tw',
 'yuoia.com',
 'gm.ncue.edu.tw',
 'student.pshs.ntct.edu.tw',
 'cyut.edu.tw',
 'webcamsexlivefree.com',
 'twysda.org',
 'afasi.gov.tw',
 'gm.youth.tc.edu.tw',
 'flps.hlc.edu.tw',
 'khvs.hcc.edu.tw',
 'ncyu.edu.tw',
 'ms25.hinet.net',
 'klcivs.kl.edu.tw',
 'creation.com.tw',
 'cts.edu.my',
 'deer.bekkr.com',
 'gm.yhsh.tn.edu.tw',
 'fhsh.tp.edu.tw',
 'vip.163.com',
 'tydep.gov.tw',
 'cc.ncue.edu.tw',
 'student2.ylsh.chc.edu.tw',
 'tsjh.tc.edu.tw',
 'fast.toobeo.com',
 'spgmail.tk',
 'gs.cgsh.tc.edu.tw',
 '1secmail.net',
 'blust.edu.tw',
 'my.cmsh.cyc.edu.tw',
 'gm.ccut.edu.tw',
 'motcmpb.gov.tw',
 'lwps.ntct.edu.tw',
 'mail.ndmctsgh.edu.tw',
 'gm.tntcsh.tn.edu.tw',
 'gapp.hcc.edu.tw',
 'st.yuhing.edu.tw',
 'sfsh.tn.edu.tw',
 'mail.ttcps.ntpc.edu.tw',
 'econgate.com',
 'gamil.com',
 'office365.ncue.edu.tw',
 'srps.ptc.edu.tw',
 'DBSCHENKER.COM',
 'longago.shop',
 'st.chjhs.tp.edu.tw',
 'tcvs.in',
 'd.blog-stuff.com',
 'mail.hcsh.tp.edu.tw',
 'turnname.com',
 'nkust.edu.tw',
 'fcu.edu.tw',
 'qiott.com',
 'gm2.nutn.edu.tw',
 'HOTMAIL.COM',
 'mail.hljh.tc.edu.tw',
 'mail.phc.edu.tw',
 'tcivs.tc.edu.tw',
 'mail1.ncnu.edu.tw',
 'stu.hlgs.hlc.edu.tw',
 'mendho.com',
 'mycamcom.com',
 'tyjh.tp.edu.tw',
 'mksh.phc.edu.tw',
 'wfes.tp.edu.tw',
 'wtkmicro.com',
 'earth.xlping.com',
 'gapps.ntust.edu.tw',
 'yahoo.com',
 'ncku.edu.tw',
 'hottestteenpornstar.com',
 'cch.org.tw',
 'stu.mlc.edu.tw',
 'cga.gov.tw',
 'mail.mof.gov.tw',
 'smail.ycsh.tp.edu.tw',
 'gm.flhs.ptc.edu.tw',
 'cdts.org.tw',
 'gms.npu.edu.tw',
 'yieldgs.com',
 'chvs.tyc.edu.tw',
 'burn.toobeo.com',
 'std.hkhs.kh.edu.tw',
 'warnne.com',
 'fda.gov.tw',
 'mail.ntou.edu.tw',
 'hsps.kh.edu.tw',
 'tsunjin.edu.my',
 'dfes.chc.edu.tw',
 'kmjh.tc.edu.tw',
 'wrap.gov.tw',
 'web20.services',
 'ms12.hinet.net',
 'jsjhs.ntct.edu.tw',
 'mail.wghs.tp.edu.tw',
 'mail.vac.gov.tw',
 'cnsh.mlc.edu.tw',
 'gms.tcu.edu.tw',
 'cavebite.com',
 'anonmails.de',
 'ewant.org',
 'swjh.tyc.edu.tw',
 'gmail.com',
 'sssh.tp.edu.tw',
 'vega.fluxyn.com',
 'ycjhs.ntct.edu.tw',
 'c.bangkokremovals.com',
 'ms58.url.com.tw',
 'streamboost.xyz',
 'twnt5.thsh.tyc.edu.tw',
 'twjh.tyc.edu.tw',
 'nhes.edu.tw',
 'outlook.com',
 'watchfreesexvideos.com',
 'weigh.zaols.com',
 'usewm.com',
 'adopt.xlping.com',
 'o365.ndhu.edu.tw',
 'mofa.gov.tw',
 'mst.hlis.hlc.edu.tw',
 'ulive.pccu.edu.tw',
 'chsps.ptc.edu.tw',
 'gm1.usc.edu.tw',
 'ms.mingdao.edu.tw',
 'vactronics.com.tw',
 'hlhs.hlc.edu.tw',
 'yandex.ru',
 'stu.cchs.chc.edu.tw',
 'nehs.tc.edu.tw',
 'taipower.com.tw',
 'dsjhs.tyc.edu.tw',
 'a.makeup.blue',
 'hs.hermes-epitek.com',
 'ought.xlping.com',
 'krjh.tc.edu.tw',
 'zjes.tyc.edu.tw',
 'getit.email',
 'hmjh.chc.edu.tw',
 'tzps.ptc.edu.tw',
 'cpshs.hcc.edu.tw',
 'student.shsh.tn.edu.tw',
 'kses.tn.edu.tw',
 'td-school.org.cn',
 'o365st.cycu.edu.tw',
 'proof.nedmr.com',
 '1000welectricscooter.net',
 'ymail.com',
 'thingstodo.pics',
 'apps.lksh.chc.edu.the',
 'gm.klps.ttct.edu.tw',
 'mail.cish.mlc.edu.tw',
 'ckvs.tyc.edu.tw',
 'mail.wsm.kh.edu.tw',
 'dsm.kh.edu.tw',
 'ntsh.ntct.edu.tw',
 'm-dnc.com',
 'smail.hc.edu.tw',
 'brain.nedmr.com',
 'stu.cshs.ntct.edu.tw',
 'era.sudeu.com',
 'hpjh.kh.edu.tw',
 'mail.hakka.gov.tw',
 'go.thu.edu.tw',
 'nuu.edu.tw',
 'mail.ntua.edu.tw',
 'std.hwhs.tc.edu.tw',
 'mail.chihlee.edu.tw',
 'woriline.com',
 'cloudapps.org.tw',
 'g2.usc.edu.tw',
 'st.cjshs.tn.com.tw',
 'tpi.tw',
 'esut.tp.edu.tw',
 'mail.nlps.hc.edu.tw',
 'hgsh.hc.edu.tw',
 'g.nccu.edu.tw',
 'wuuvo.com',
 'web-club.eu',
 'slps.tn.edu.tw',
 'kcjh.ptc.edu.tw',
 'dns.chanes.tc.edu.tw',
 'st.thsh.tp.edu.tw',
 'gm.asia.edu.tw',
 'cyhs.tp.edu.tw',
 'burmancoffeedev.store',
 'gm.pu.edu.tw',
 'tn.edu.tw',
 '1secmail.org',
 'mutide.com',
 'ylsh.chc.edu.tw',
 'hermes-testing.com.tw',
 'misshalls.org',
 'cloud.ssvs.tp.edu.tw',
 'coltrane6.hexagonaldrawings.com',
 'gmail.cim',
 'ms01.ssivs.chc.edu.tw',
 'ymsh.hcc.edu.tw',
 'tmu.edu.tw',
 'g.clvs.tyc.edu.tw',
 'gafe.cksh.tp.edu.tw',
 'ntsu.edu.tw',
 'gs.nfu.edu.tw',
 'mlsh.mlc.edu.tw',
 'mail2.khgs.tn.edu.tw',
 'getnada.com',
 'ms1.ylh.gov.tw',
 'orientstargroup.com',
 'foot.toobeo.com',
 'gm.mhchcm.edu.tw',
 'stu.tcssh.tc.edu.tw',
 'st.ptes.tp.edu.tw',
 'justdessertspreview.com',
 'mail.jges.ntpc.edu.tw',
 'nycu.edu.tw',
 'shavers.hair',
 'thaimail.live',
 'ms.ttu.edu.tw',
 'rest.bekkr.com',
 'ms2.hinet.net',
 'email.klepb.gov.tw',
 'g.makeup.blue',
 'apps.ycvs.tn.edu.tw',
 'nmps.tyc.edu.tw',
 'khjh.hc.edu.tw',
 'ntchps.ntct.edu.tw',
 'ttc.edu.tw',
 'grandon.browndecorationlights.com',
 'mail.tumt.edu.tw',
 'gm.hccvs.hc.edu.tw',
 'gm2.fxsh.tyc.edu.tw',
 'sina.com',
 'ms2.cshs.kh.edu.tw',
 'csh.org.tw',
 'takming.edu.tw',
 'yljh.mlc.edu.tw',
 'nutc.edu.tw',
 'event.bekkr.com',
 'mood.toobeo.com',
 'cyes.tyc.edu.tw',
 'mail.yzu.edu.tw',
 'gcps.ptc.edu.tw',
 'st.hchs.ntpc.edu.tw',
 'cogsh.tp.edu.tw',
 'ms2.hssh.tp.edu.tw',
 'mail.smgsh.tc.edu.tw',
 'fectode.com',
 'mdais.gov.tw',
 'hotmail.com.tw',
 'alumni.ccsh.tp.edu.tw',
 'mass.xlping.com',
 'm365.fju.edu.tw',
 'elvs.chc.edu.tw',
 'gap.wzu.edu.tw',
 'webmail.ntpu.edu.tw',
 'tcsh.hlc.edu.tw',
 'mail.nchu.edu.tw',
 'xrumer.app',
 'step.xlping.com',
 'student.kjsh.ntpc.edu.tw',
 'morglory.com.tw',
 'gmale.com',
 'smps.hlc.edu.tw',
 'wagor.tc.edu.tw',
 'taivs.tp.edu.tw',
 'jarocki.hexagonaldrawings.com',
 'wishwit.com',
 'mpi.com.tw',
 'stdmail.nssh.ntpc.edu.tw',
 'mail.usc.edu.tw',
 'focus.nedmr.com',
 'syps.kh.edu.tw',
 'o365.au.edu.tw',
 'thingstodoin.shop',
 'xiuset.com',
 'a.1000welectricscooter.com',
 'hhjh.tp.edu.tw',
 'mailbab.com',
 'gm.cyut.edu.tw',
 'ntpc.gov.tw',
 'sharklasers.com',
 'album.nedmr.com',
 'gmx.com',
 'wes.tc.edu.tw',
 'nctu.edu.tw',
 'wlps.ptc.edu.tw',
 'cavemao.com',
 'motherinlawsex.com',
 'mariarmy.com',
 'ts.ptc.edu.tw',
 'cwlf.org.tw',
 'gsuite.essh.kl.edu.tw',
 'mail.cjcu.edu.tw',
 'mail.nknu.edu.tw',
 'thu.edu.tw',
 'kiankok.edu.my',
 'super.papte.com',
 'dtjh.mlc.edu.tw',
 'gm.ntcu.edu.tw',
 'clvsc.tyc.edu.tw',
 'dry.zaols.com',
 'stu.dwhs.tn.edu.tw',
 'email.nchu.edu.tw',
 'webcamporntubes.com',
 'cgu.edu.tw',
 'staff.nkuht.edu.tw',
 'grad.ntue.edu.tw',
 'freeadultcamtocam.com',
 'gmail.con',
 'stu.lchs.kh.edu.tw',
 'sfaa.gov.tw',
 'jwsh.tp.edu.tw',
 'gm.pttsh.ttct.edu.tw',
 'shsh.tw',
 'mail.gjsh.ntpc.edu.tw',
 'nkust.edu.the',
 'cloudinfo.com.tw',
 'kssh.khc.edu.tw',
 'wondroustravel.online',
 'ntes.ntct.edu.tw',
 'hles.tyc.edu.tw',
 'f.most-wanted-stuff.com',
 'ms32.hinet.net',
 'twu.edu.tw',
 'usinadvance.com.tw',
 'yh.tp.edu.tw',
 'nnjh.kl.edu.tw',
 'taisugar.com.tw',
 'mail2.nccu.tw',
 'liedke62.lumbermilltricks.com',
 'mlc.edu.tw',
 'shinmin.tc.edu.tw',
 'kpvs.tp.edu.tw',
 'gm.ttu.edu.tw',
 'mail.nptu.edu.tw',
 'gms.nutc.edu.tw',
 'hotmail.com',
 'mhjh.tp.edu.tw',
 'incisives.com',
 'nmns.edu.tw',
 'cast.toobeo.com',
 'topfreecamsites.com',
 'email.chcg.gov.tw',
 'gmal.com',
 'tdrive.thu.edu.tw',
 'gm.ahjh.tc.edu.tw',
 'gate.sinica.edu.tw',
 'mail.jjps.kh.edu.tw',
 'mail.moj.gov.tw',
 'wagas.com.tw',
 'live.fy.edu.tw',
 'gwjh.hc.edu.tw',
 'nkhs.tn.edu.tw',
 'ntu.edu.tw',
 'apps.lash.chic.edu.tw',
 'stu.chhs.hcc.edu.tw',
 'freenudesexvideos.com',
 'kuencheng.edu.my',
 'worldpeace.org.tw',
 'stu.ccsh.tp.edu.tw',
 'gm.nuts.edu.tw',
 'o365.tku.edu.tw',
 'ms7.hinet.net',
 'ntnu.edu.tw',
 'nehs.hc.edu.tw',
 'a.thailandmovers.com',
 'visagency.us',
 'pcps.ptc.edu.tw',
 'fhes.tn.edu.tw',
 'hk.edu.tw',
 'mail.ntut.edu.tw',
 'rayford69.dynainbox.com',
 'whsh.tc.edu.tw',
 'cksh.chc.edu.tw',
 'dmhs.kh.edu.tw',
 'hcvs.hc.edu.tw',
 'nzsmr.kh.edu.tw',
 'gm.cnu.tw',
 'apps.lksh.chc.edu.te',
 'cute.edu.tw',
 'ptjh.tp.edu.tw',
 'mail.lhu.edu.tw',
 'itri.org.tw',
 'iasme.nat.gov.tw',
 'ghps.ptc.edu.tw',
 'ylshb.gov.tw',
 'go.edu.tw',
 'kmu.edu.tw',
 'smsh.ntpc.edu.tw',
 'jsp.kh.edu.tw',
 'mail.ncyu.edu.tw',
 'email.nlhs.tyc.edu.tw',
 'gm2.usc.edu.tw',
 'gmes.tyc.edu.tw',
 'sexpone.com',
 'hjgs.cy.edu.tw',
 'app.mzu.kh.edu.tw',
 'apps.lash.ccc.edu.tw',
 'ms22.hinet.net',
 'b.thailandmovers.com',
 'tap.sudeu.com',
 'tyjh.tc.edu.tw',
 'student.cysh.cy.edu.tw',
 'g2.nctu.edu.tw',
 'np.gigabyte.com',
 'tcvs.ilc.edu.tw',
 'tsps.cyc.edu.tw',
 'hwsh.ylc.edu.tw',
 'mail.fju.edu.tw',
 'ptgsh.ptc.edu.tw',
 'tysh.tyc.edu.tw',
 'mail.ctsh.hcc.edu.tw',
 'ycsh.tp.edu.tw',
 'kelzer.dynainbox.com',
 'cres.tc.edu.tw',
 'mean.bekkr.com',
 'sipa.gov.tw',
 'begin.bekkr.com',
 'cpshs.org.tw',
 'designmsu.ru',
 'gm7.usc.edu.tw',
 'tkgsh.tn.edu.tw',
 'live.ntpc.edu.tw',
 'mail.caa.gov.tw',
 'cyvs.tyc.edu.tw',
 'ftm.kh.edu.tw',
 'ms6.hinet.net',
 'chash.chc.edu.tw',
 'rwm.kh.edu.tw',
 'gayu.biz',
 'cksh.hc.edu.tw',
 'wondrouslamaison.com',
 'm1.lses.tyc.edu.tw',
 'ctcn.edu.tw',
 'gm.tnfsh.tn.edu.tw',
 'mmc.edu.tw',
 'savedaday.com',
 'stu.trgsh.tp.edu.tw',
 'ms.tcjh.ntpc.edu.tw',
 'gm.ntpu.edu.tw',
 'wlgsh.tp.edu.tw',
 'pu.edu.tw',
 'ndhu.edu.tw',
 'stu.edu.tw',
 'kuehne-nagel.com',
 'mail.nou.edu.tw',
 'seed.net.tw',
 'gtrial.ctust.edu.tw',
 'stone.toobeo.com',
 'bigbucks.info',
 'mos.com.tw',
 'stu.sggs.hc.edu.tw',
 'jerseyshoreelectric.com',
 'gm.kl.edu.tw',
 'ms17.hinet.net',
 'asia.dnsabr.com',
 'btsflip.com',
 'anpencs.com',
 'gfes.ntpc.edu.tw',
 'cyhs.tc.edu.tw',
 'ntes.tc.edu.tw',
 'msn.com',
 'ycsh.cyc.edu.tw',
 'clc.tku.edu.tw',
 'firstmailler.net',
 'fhsh.khc.edu.tw',
 'cc.dystcs.kh.edu.tw',
 'mail2.cjhs.kh.eud.tw',
 'asia.edu.tw',
 'ms8.hinet.net',
 'mail.fcu.edu.tw',
 'urfer.dynainbox.com',
 'sadolsky.hexagonaldrawings.com',
 'hshs.tyc.edu.tw',
 'ms34.hinet.net',
 'm2.gijh.tyc.edu.tw',
 'sfps.ntpc.edu.tw',
 'whps.tp.edu.tw',
 'stumail.nutn.edu.tw',
 'mail.kmsh.tn.edu.tw',
 'tea.nknush.kh.edu.tw',
 'mail.tnssh.tn.edu.tw',
 'makeup.blue',
 'app.aodi.ntpc.edu.tw',
 'blsh.tp.edu.tw',
 'bwjh.ylc.edu.tw',
 'mpb.gov.tw',
 'hhsh.cy.edu.tw',
 'freesexcamsites.com',
 'yjvs.chc.edu.tw',
 'web.bookmarkclup.com',
 'std.dysh.tyc.edu.tw',
 'student.wzu.edu.tw',
 'iot.gov.tw',
 'student.szmc.edu.tw',
 'top.toobeo.com',
 'sacheart.org.tw',
 'cjps.ptc.edu.tw',
 'ycjh.hlc.edu.tw',
 'spl.com.tw',
 'epa.gov.tw',
 'basic.zaols.com',
 'hsiaohospital.org',
 'g.whes.tyc.edu.tw',
 'pcps.ntpc.edu.tw',
 'm2k.com.tw',
 'lsps.ntct.edu.tw',
 'mail.hpsh.tp.edu.tw',
 'groupwagon.com',
 'twivs.tn.edu.tw',
 'nnjh.tn.edu.tw',
 'iCloud.com',
 'htcsqa.com',
 'mailclass.tlsh.tp.edu.tw',
 'lssh.tp.edu.tw',
 'ms46.hinet.net',
 'stu.cmsh.khc.edu.tw',
 'ncc.gov.tw',
 'net2100.com.tw',
 'dasemana.com',
 'argue.papte.com',
 'gm.student.ncut.edu.tw',
 'gms.tku.edu.tw',
 'stu.wghs.tp.edu.tw',
 'picher.hexagonaldrawings.com',
 'ms68.hinet.net',
 'dila.edu.tw',
 'ovallo.com',
 'stust.edu.tw',
 'stu.ctas.tc.edu.tw',
 'stu.tshs.tp.edu.tw',
 'mlsh.tp.edu.tw',
 'chatsexylive.com',
 'std.tcfsh.tc.edu.tw',
 'mail.cnu.edu.tw',
 'ems.hccg.gov.tw',
 'me.com',
 'tcps.tn.edu.tw',
 'gm.scu.edu.tw',
 'gges.tp.edu.tw',
 'nsjh.ylc.edu.tw',
 'NKUST.EDU.TW',
 'customs.gov.tw',
 'menterprise.app',
 'gas.fgu.edu.tw',
 'ms6.pmsh.khc.edu.tw',
 'nkust.due.tw',
 'tses.cyc.edu.tw',
 'gl.ck.tp.edu.tw',
 'mail2.blsh.tp.edu.tw',
 'chepb.gov.tw',
 'smjh.hc.edu.tw',
 'stu.japs.tp.edu.tw',
 'paps.kh.edu.tw',
 'chgsh.chc.edu.tw',
 'ludlow3.browndecorationlights.com',
 'premtek.com.tw',
 'truth.toobeo.com',
 'hungtai.com.tw',
 'mail2.cjhs.kh.edu.tw',
 'kcislk.ntpc.edu.tw',
 'peichia.com',
 'consultingservice.shop',
 'linkbuilding.ink',
 'bbitj.com',
 'quelbroker.com',
 'skes.tc.edu.tw',
 'kcis.com.tw',
 'oca.gov.tw',
 'ctust.edu.tw',
 'syjhs.tc.edu.tw',
 'st.ssivs.chc.edu.tw',
 'shjh.ylc.edu.tw',
 'nakedgirlass.com',
 'ms.hcjh.chc.edu.tw',
 'mail.aeust.edu.tw',
 'kfsh.hc.edu.tw',
 'gtvision.com.tw',
 'kcg.gov.tw',
 'yphs.tw',
 'ms9.hinet.net',
 'range.bekkr.com',
 'o.web20.services',
 'gsamail.live',
 'cloud.isu.edu.tw',
 'mail.hkhs.kh.edu.tw',
 'shavers.skin',
 'hmail.com',
 'cn.hermes-epitek.com',
 'videopornsite.com',
 'gmail.com.tw',
 'freindin.site',
 'cycu.org.tw',
 'mail.ncnu.edu.tw',
 'changtax.gov.tw',
 'email.tyhs.edu.tw',
 'mail.hhjh.hc.edu.tw',
 'gorney.hexagonaldrawings.com',
 'ehuayu.org',
 'era.toobeo.com',
 'foryou-fu.com.tw',
 'st.cjshs.tan.edu.tw',
 'mydreamsex.com',
 'ljsh.hcc.edu.tw',
 'fdes.chc.edu.tw',
 'cycu.edu.tw',
 'g.ntsh.ntpc.edu.tw',
 'tksh.ntpc.edu.tw',
 'csps.ptc.edu.tw',
 'skydigient.com',
 'fsnps.ntct.edu.tw',
 'mail.ylc.edu.tw',
 'vtsh.tc.edu.tw',
 'wfsh.tp.edu.tw',
 'yuntech.edu.tw',
 'hsjh.chc.edu.tw',
 'treewake.com',
 'mevori.com',
 'cyvs.cy.edu.tw',
 'sljh.hcc.edu.tw',
 'nccu.edu.tw',
 'mail.dhes.tyc.edu.tw',
 'bheps.com',
 'cdes.ptc.edu.tw',
 'mail.hwsh.tc.edu.tw',
 'tea.ntue.edu.tw',
 'nptu.edu.tw',
 'student.tdsb.on.ca',
 'dgejh.ntpc.edu.tw',
 'student.nqu.edu.tw',
 'ms.tsh.ttu.edu.tw',
 'wses.hcc.edu.tw',
 'nsysu.edu.tw',
 'naver.com',
 'O365st.cycu.edu.tw',
 'm2.pyjh.chc.edu.tw',
 'savs.hcc.edu.tw',
 'vghtpe.gov.tw',
 'mailsnode.com',
 'hdsh.ilc.edu.tw',
 'crps.ptc.edu.tw',
 'dxhs.tyc.edu.tw',
 'yahoo.co.jp',
 'sexcamscom.com',
 'apps.ccsh.ptc.edu.tw',
 'apps.lksh.chic.edu.tw',
 'ylsh.hlc.edu.tw',
 'lmsh.tn.edu.tw',
 'apps.lksh.chc.edu.tw',
 'mail.feu.edu.tw',
 'tlhc.ylc.edu.tw',
 'weic.idv.tw',
 'ms.ly.kh.edu.tw',
 'nkustedu.tw',
 'stu.hdsh.ilc.edu.tw',
 'stu.tnssh.tn.edu.tw',
 'ccjh.ptc.edu.tw',
 'mom.ceako.com',
 'bigwomensexvideo.com',
 'cdsh.ilc.edu.tw',
 'sish.ntpc.edu.tw',
 'mail.e-land.gov.tw',
 '1utar.my',
 'tshcmc.edu.vn',
 'ms2.kghs.kh.edu.tw',
 'office.stust.edu.tw',
 'mailnesia.com',
 'email.nzjh.ptc.edu.tw',
 'yahoo.com.tw',
 'ms85.url.com.tw',
 'ms31.hinet.net',
 'smail.ilc.edu.tw',
 'go.isu.edu.tw',
 'gjjh.tp.edu.tw',
 'gapps.ntnu.edu.tw',
 'yssh.tc.edu.tw',
 'jnes.ylc.edu.tw',
 'epza.gov.tw',
 'isu.edu.tw',
 'smail.phc.edu.tw',
 'mail4.store',
 'mail.shu.edu.tw',
 'bowmer16.lumbermilltricks.com',
 'close.toobeo.com',
 'allow.bekkr.com',
 'goog.ptsh.ntct.edu.tw',
 'worldvision.org.tw',
 'gapps.fg.tp.edu.tw',
 'csps.chc.edu.tw',
 'hcd.org.tw',
 'smail.cyc.edu.tw',
 'cumonteentits.com',
 'stu.kjes.tp.edu.tw',
 'mail.coa.gov.tw',
 'dcctb.com',
 'bob.tw',
 'g.ntu.edu.tw',
 'csmu.edu.tw',
 'tyhs.kh.edu.tw',
 'yh.tp.edutw',
 'g.ncyu.edu.tw',
 'adjh.tn.edu.tw',
 'ntpc.edu.tw',
 'tsmc.com',
 'view.bekkr.com',
 'lickingupcum.com',
 'gm.csmu.edu.tw',
 'phmhs.phc.edu.tw',
 'swiroc.com',
 'o365.mhchcm.edu.tw',
 'cgmh.org.tw',
 'cchs.kh.edu.tw',
 'akhs.ntpc.edu.tw',
 'goes.mlc.edu.tw',
 'dysh.tyc.edu.tw',
 'cmp.com.tw',
 'penla.mlc.edu.tw',
 'ctps.ptc.edu.tw',
 'mail.saes.tyc.edu.tw',
 'niu.edu.tw',
 'chjhs.tyc.edu.tw',
 'ms77.hinet.net',
 'dtes.ptc.edu.tw',
 'ocac.gov.tw',
 'GMAIL.COM',
 'shipypl.com',
 'stmail.nptu.edu.tw',
 'stu.dlsh.tc.edu.tw',
 'shps.kh.edu.tw',
 'dnatest.news',
 'gemail.yuntech.edu.tw',
 'businessconsulting.shop',
 'porndvdstream.com',
 'wybuwy.xyz',
 'gcloud.rssh.tw',
 'frozenfood.com.tw',
 'princes.website',
 'hnhexpress.com',
 'livemail.tw',
 'hch.gov.tw',
 'gm.nssh.ntpc.edu.tw',
 'f.chestpain.one',
 'mail.tainan.gov.tw',
 'freehdstreamingporn.com',
 'pm.me',
 'ttct.edu.tw',
 'sdhs.notch.edu.tw',
 'morrisonexpress.com',
 'nkust.edu.TW',
 'lgjh.ptc.edu.tw',
 'ms24.hinet.net',
 'enhancedzoom.com',
 'gmaio.com',
 'stes.ntpc.edu.tw',
 'elektromir-amp.ru',
 'zcjh.ntpc.edu.tw',
 'ms2.ccsh.tn.edu.tw',
 'cmu.edu.tw',
 'g.1000welectricscooter.com',
 'math.fju.edu.tw',
 '5spc.npa.gov.tw',
 'st.cjshs.tn.edu.tw',
 'yao.tw',
 'folhadobrasil.top',
 'gs.ncku.edu.tw',
 'smilietoys.com',
 'stu.nknush.kh.edu.tw',
 'nptups.ptc.edu.tw',
 'chsc.tw',
 'hcu.edu.tw',
 'hlbh.hlc.edu.tw',
 'mailst.cjcu.edu.tw',
 'e.razore100.fans',
 'ksvs.kh.edu.tw',
 'apps.mcsh.kh.edu.tw',
 'alum.ccu.edu.tw',
 'gapp.fju.edu.tw',
 'hshs.chc.edu.tw',
 'g-mail.nsysu.edu.tw',
 'msa.hinet.net',
 'lsjh.tp.edu.tw',
 'wces.tc.edu.tw',
 'live.csmu.edu.tw',
 'himax.com.tw',
 'ntub.edu.tw',
 'kimo.com',
 'gm.usc.edu.tw',
 'mch.org.tw',
 'sce.pccu.edu.tw',
 'hchs.kh.edu.tw',
 'smc.edu.tw',
 'prestawebexperts.com',
 '1000welectricscooter.com',
 'gs.takming.edu.tw',
 'fy.edu.tw',
 'radican90.lumbermilltricks.com',
 'yourmail.wiki',
 'seek.xlping.com',
 'stu.dles.tyc.edu.tw',
 'smail.tnjh.ylc.edu.tw',
 'bdps.kl.edu.tw',
 'cgcbn.com',
 'mail.ilosh.gov.tw',
 'tcjh.tyc.edu.tw',
 '1secmail.com',
 'ms2.cdjh.hc.edu.tw',
 'bcaccept.com',
 'b.wirelesschargers.xyz',
 'outlook.my',
 'wses.tn.edu.tw',
 'chonghwakl.edu.my',
 'stu.shinmin.tc.edu.tw',
 'tcjhs.tyc.edu.tw',
 'mail.lhps.kh.edu.tw',
 'yucsh.tp.edu.tw',
 'adamson.edu.ph',
 'ems.chiayi.com.tw',
 'Gmail.com',
 'tncghb.gov.tw',
 'tchcvs.tw',
 'qq.com',
 'nhsh.tp.edu.tw',
 'goo-dong.com',
 'pose.xlping.com',
 'hljh.tc.edu.tw',
 'form.toobeo.com',
 'pths.ptc.edu.tw',
 'strategyconsulting.site',
 'ems.niu.edu.tw',
 'stand.nedmr.com',
 'student.hjgs.cy.edu.tw',
 'ylhc.tw',
 'a.skincareproductoffers.com',
 'ivyjhs.tc.edu.tw',
 'ykjh.tn.edu.tw',
 'tcfsh.tc.edu.tw',
 'filmseria.com',
 'massingale.browndecorationlights.com',
 'mail.edu.tw',
 'gm.ptes.tp.edu.tw',
 'mljh.ylc.edu.tw',
 'wda.gov.tw',
 'me.mcu.edu.tw',
 'm1.tlsh.ylc.edu.tw',
 'std.fhvs.ntpc.edu.tw',
 'clsh.ntpc.edu.tw',
 'claim.verywd.com',
 'cloud.zaols.com',
 '365.niu.edu.tw',
 'gm.cute.edu.tw',
 'dtjh.ptc.edu.tw',
 'hlc.edu.tw',
 'lzsh.tc.edu.tw',
 'maker.xlping.com',
 'dcsh.tp.edu.tw',
 'fssh.khc.edu.tw',
 '777.tw',
 'newestteenpornstars.com',
 'sysh.tc.edu.tw',
 'railway.gov.tw',
 'yuteh.ntpc.edu.tw',
 'fsjh.kh.edu.tw',
 'dyjhs.tyc.edu.tw',
 'bfirstmail.com',
 'yahoo.com.hk',
 'kkfoods.com.tw',
 'swsh.hlc.edu.tw',
 'ltsh.tyc.edu.tw',
 'hzsh.tc.edu.tw',
 'ndes.tyc.edu.tw',
 'pjhs.tyc.edu.tw',
 'gm.hnvs.cy.edu.tw',
 'changswonderland.tw',
 'cdjh.hc.edu.tw',
 'chsh.chc.edu.tw',
 'gm.ym.edu.tw',
 'hbps.ptc.edu.tw',
 'prhs.ptc.edu.tw',
 'st.tc.edu.tw',
 'hhhs.tp.edu.tw',
 '163.com',
 'skgsh.tn.edu.tw',
 'spes.ptc.edu.tw',
 'none.zaols.com',
 'whattodo.beauty',
 'mail.sips.ntpc.edu.tw',
 'gm.klms.ntou.edu.tw',
 'tfjhs.ntct.edu.tw',
 'sggs.hc.edu.tw',
 'ms14.hinet.net',
 'mail.chsh.ntct.edu.tw',
 'h.thailandmovers.com',
 'student.tajen.edu.tw',
 'wahlee.com',
 'etc.org.tw',
 'longago.pics',
 'gapp.nthu.edu.tw',
 'simes.tyc.edu.tw',
 'ocu.edu.tw',
 'ntou.edu.tw',
 'supportgm.com',
 'ncnu.edu.tw',
 'ms11.hinet.net',
 'dpps.ptc.edu.tw',
 'st.nksh.tyc.edu.tw',
 'ntut.edu.tw',
 'st.cish.mlc.edu.tw',
 'mail.elsh.chc.edu.tw',
 'tari.gov.tw',
 'tmail.ilc.edu.tw',
 'm2.csghs.tp.edu.tw',
 'openzem.com',
 'apps.csps.hc.edu.tw',
 'fjuclinic.com',
 'smhs.kh.edu.tw',
 'mail2.smes.tyc.edu.tw',
 'tkps.ntct.edu.tw',
 'nkust.edu.com',
 'yandex.com',
 'guide.toobeo.com',
 'gms.ndhu.edu.tw',
 'stu.ctsh.hcc.edu.tw',
 'yges.ptc.edu.tw',
 'risekka.com',
 'mail.tycg.gov.tw',
 'wfps.tp.edu.tw',
 'apps.ntpc.edu.tw',
 'ms.niu.edu.tw',
 'ymhs.tyc.edu.tw',
 'gm.chihlee.edu.tw',
 'b.skincareproductoffers.com',
 'htsh.ntpc.edu.tw',
 'cdps.ntpc.edu.tw',
 'jmjh.tn.edu.tw',
 'cyivs.cy.edu.tw',
 'live.com',
 'gm.phjh.tc.edu.tw',
 'chc.edu.tw',
 'o365.tsshs.ntpc.edu.tw',
 'g.pccu.edu.tw',
 'yses.tn.edu.tw',
 'mlvs.mlc.edu.tw',
 'ms96.url.com.tw',
 'gmbni.com',
 'hyps.ntct.edu.tw',
 'ylsh.mlc.edu.tw',
 ...]

In [75]:

domain_list = ["edu.tw", "gmail", "qq", "yahoo", "hotmail"]
each_domain_count_list = [len([i for i in domain_name_list if d in i]) for d in domain_list]
each_domain_count_list

[15931, 14337, 139, 538, 205]

In [105]:
data = {'domain': domain_list + ["other"],
        'count': each_domain_count_list + [len(domain_name_list) - sum(each_domain_count_list)]}

domain_count_df = pd.DataFrame(data)
domain_count_df

    domain  count
0   edu.tw  15931
1    gmail  14337
2       qq    139
3    yahoo    538
4  hotmail    205
5    other   5999

In [112]:
domain_count_df['domain'][domain_count_df['count'] == domain_count_df['count'].max()].values[0]

'edu.tw'

## country

In [100]:
register20230717_df['country'] = register20230717_df['country'].replace(['""'], '未填')
country_count_df = pd.DataFrame(register20230717_df['country'].value_counts())
country_count_df.reset_index(inplace=True)
country_count_df.columns = ["country", "count"]
country_count_df.head(20) #.values

   country  count
0       TW  22484
1       未填  11098
2       MY   1533
3       CN    381
4       VN     56
5       PY     54
6       HK     40
7       ID     32
8       JP     30
9       TH     22
10      MO     18
11      US     18
12      AL     17
13      PK     15
14      AU     15
15      AE     12
16      GM     12
17      CA     12
18      KR     12
19      DE     11

In [104]:
# https://www.cbc.gov.tw/public/attachment/83189591771.pdf
country_dict = {
    'TW' : '台灣', 'MY' : '馬來西亞', 'CN' : '中國大陸', 'VN' : '越南', 'PY' : '巴拉圭', 
    'HK' : '香港', 'ID' : '印尼', 'JP' : '日本', 'TH' : '泰國', 'MO' : '澳門',
    'US' : '美國', 'AL' : '阿爾巴尼亞', 'PK' : '巴基斯坦', 'AU' : '澳大利亞', 'AE' : '阿拉伯聯合大公國', 
    'GM' : '甘比亞', 'CA' : '加拿大', 'KR' : '韓國', 'DE' : '德國', 'PH' : '菲律賓', 
    'IE' : '愛爾蘭','CY' : '塞普路斯', 'GB' : '英國', 'FR' : '法國', 'LU' : '盧森堡', 
    'TF' : '法屬南部屬地', 'PM' : '聖匹及密啟倫群島', 'SV' : '薩爾瓦多', 'MS' : '蒙瑟拉特島', 'BH' : '巴林', 
    'AF' : '阿富汗', 'SD' : '蘇丹'}
country_count_df.replace({"country": country_dict},inplace=True)
country_count_df

    country  count
0        台灣  22484
1        未填  11098
2      馬來西亞   1533
3      中國大陸    381
4        越南     56
..      ...    ...
243      UZ      1
244      UG      1
245      JM      1
246      TD      1
247      SM      1

[248 rows x 2 columns]

In [102]:
country_count_df.country.values

array(['TW', '未填', 'MY', 'CN', 'VN', 'PY', 'HK', 'ID', 'JP', 'TH', 'MO',
       'US', 'AL', 'PK', 'AU', 'AE', 'GM', 'CA', 'KR', 'DE', 'PH', 'IE',
       'CY', 'GB', 'FR', 'LU', 'TF', 'PM', 'SV', 'MS', 'BH', 'AF', 'SD',
       'GE', 'CW', 'LT', 'PR', 'NR', 'EC', 'IQ', 'KG', 'TM', 'MN', 'BL',
       'GW', 'KZ', 'PF', 'KP', 'BY', 'AQ', 'YT', 'PW', 'AS', 'DZ', 'LR',
       'QA', 'HN', 'MM', 'RO', 'PE', 'CU', 'CO', 'MZ', 'SG', 'SH', 'TC',
       'BZ', 'MX', 'SY', 'IN', 'BV', 'BB', 'HR', 'MG', 'GU', 'CR', 'ML',
       'NE', 'GG', 'SB', 'MH', 'ER', 'CG', 'PT', 'KE', 'NL', 'TJ', 'MD',
       'ZW', 'OM', 'LA', 'AR', 'FI', 'PA', 'FJ', 'GL', 'AW', 'EH', 'SI',
       'LV', 'SE', 'MF', 'ZM', 'VC', 'BT', 'MK', 'TN', 'NG', 'UM', 'IT',
       'CF', 'GD', 'GA', 'MP', 'JO', 'VG', 'DK', 'LK', 'BN', 'PL', 'ET',
       'SZ', 'TG', 'CH', 'DJ', 'TK', 'CC', 'MT', 'TR', 'GQ', 'JE', 'VU',
       'BG', 'IR', 'LC', 'NZ', 'GS', 'YE', 'MV', 'SL', 'SC', 'EG', 'IM',
       'TT', 'KM', 'RU', 'WS', 'NC', 'DM', 'UA', 'MW', 'NF', 'MA', 'CL',
       'PG', 'MQ', 'BE', 'BM', 'IO', 'AT', 'TV', 'WF', 'ES', 'LB', 'BA',
       'CK', 'ST', 'EE', 'AZ', 'NO', 'PN', 'FK', 'LY', 'MR', 'VI', 'NI',
       'MC', 'AO', 'GY', 'SA', 'IS', 'PS', 'SO', 'KH', 'BJ', 'LI', 'CI',
       'VA', 'SN', 'AG', 'VE', 'CX', 'SR', 'UY', 'CD', 'MU', 'FM', 'ZA',
       'BO', 'SS', 'TL', 'BF', 'TO', 'CV', 'DO', 'RE', 'GR', 'BS', 'BW',
       'HT', 'BR', 'GP', 'NP', 'GF', 'KW', 'KN', 'GH', 'HU', 'RW', 'HM',
       'FO', 'TZ', 'GI', 'CM', 'AX', 'BI', 'ME', 'SX', 'LS', 'CZ', 'IL',
       'SJ', 'KY', 'AD', 'GT', 'SK', 'NU', 'AI', 'GN', 'KI', 'BQ', 'RS',
       'BD', 'UZ', 'UG', 'JM', 'TD', 'SM'], dtype=object)

## education level